#!/usr/bin/env python3
"""Generate LaTeX tables summarizing MFQ moral foundation profiles for models and personas."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, Iterable, Sequence, Tuple

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from analysis.diagnostics.plot_relevance_profiles import (
    FOUNDATION_ORDER as SELF_FOUNDATIONS,
    load_relevance_scores,
    summarise_scores,
)
from analysis.diagnostics.plot_persona_relevance_profiles import (
    FOUNDATION_ORDER as PERSONA_FOUNDATIONS,
    available_personas,
    load_persona_scores,
    summarise_persona_scores,
)

SELF_TABLE_PATH = Path("articles") / "table_moral_foundations_profiles.tex"
PERSONA_TABLE_PATH = Path("articles") / "table_persona_moral_foundations_profiles.tex"
DEFAULT_PERSONA_IDS = [25, 75, 86]

MODEL_DISPLAY_NAMES = {
    "claude-haiku-4-5": "Claude Haiku 4.5",
    "claude-sonnet-4-5": "Claude Sonnet 4.5",
    "deepseek-v3": "DeepSeek V3",
    "deepseek-v3.1": "DeepSeek V3.1",
    "gemini-2.5-flash": "Gemini 2.5 Flash",
    "gemini-2.5-flash-lite": "Gemini 2.5 Flash Lite",
    "gpt-4.1": "GPT-4.1",
    "gpt-4.1-mini": "GPT-4.1 Mini",
    "gpt-4.1-nano": "GPT-4.1 Nano",
    "gpt-4o": "GPT-4o",
    "gpt-4o-mini": "GPT-4o Mini",
    "grok-4": "Grok 4",
    "grok-4-fast": "Grok 4 Fast",
    "llama-4-maverick": "Llama 4 Maverick",
    "llama-4-scout": "Llama 4 Scout",
}


def format_entry(mean: float, se: float) -> str:
    return f"${mean:.2f}\\pm{se:.2f}$"


def write_tabular(
    output_path: Path,
    headers: Iterable[str],
    rows: Iterable[Tuple[str, Iterable[str]]],
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    header_cells = " & ".join(headers)
    col_spec = "l" + "c" * (len(headers) - 1)
    lines = ["% Auto-generated by analysis/generate_relevance_profile_tables.py"]
    backslash = "\\"
    row_break = backslash * 2
    lines.append(f"{backslash}begin{{tabular}}{{{col_spec}}}")
    lines.append("  " + backslash + "toprule")
    lines.append(f"  {header_cells} {row_break}")
    lines.append("  " + backslash + "midrule")
    for row_label, row_entries in rows:
        row_str = " & ".join((row_label, *row_entries))
        lines.append(f"  {row_str} {row_break}")
    lines.append("  " + backslash + "bottomrule")
    lines.append(backslash + "end{tabular}")
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def generate_self_table(output_path: Path) -> None:
    scores_by_model = load_relevance_scores()
    summaries = summarise_scores(scores_by_model)
    headers = ["Model", *SELF_FOUNDATIONS]
    rows = []
    for model in sorted(summaries):
        entries = [format_entry(*summaries[model][foundation]) for foundation in SELF_FOUNDATIONS]
        rows.append((MODEL_DISPLAY_NAMES.get(model, model.replace("openrouter-", "")), entries))
    # aggregate across models in the no-persona condition
    if summaries:
        aggregated = {}
        for foundation in SELF_FOUNDATIONS:
            means = []
            ses = []
            for model_summary in summaries.values():
                mean_val, se_val = model_summary[foundation]
                means.append(mean_val)
                ses.append(se_val)
            mean_avg = sum(means) / len(means)
            se_combined = (sum(se ** 2 for se in ses) ** 0.5) / len(ses)
            aggregated[foundation] = (mean_avg, se_combined)
        rows.append(("Average (no persona)", [format_entry(*aggregated[f]) for f in SELF_FOUNDATIONS]))
    write_tabular(output_path, headers=headers, rows=rows)


def collect_personas(persona_ids: Sequence[int]) -> Tuple[Iterable[int], Dict[int, Dict[str, Tuple[float, float]]]]:
    available = set(available_personas())
    selected = sorted(set(persona_ids))
    missing = [persona_id for persona_id in selected if persona_id not in available]
    if missing:
        raise ValueError(f"Requested personas are unavailable: {missing}")
    scores = load_persona_scores(set(selected))
    summaries = summarise_persona_scores(scores)
    return selected, summaries


def generate_persona_table(output_path: Path, persona_ids: Sequence[int]) -> None:
    persona_ids, summaries = collect_personas(persona_ids)
    headers = ["Persona", *PERSONA_FOUNDATIONS]
    rows = []
    for persona in persona_ids:
        if persona not in summaries:
            continue
        entries = [
            format_entry(*summaries[persona][foundation])
            for foundation in PERSONA_FOUNDATIONS
        ]
        rows.append((str(persona), entries))
    if not rows:
        raise ValueError("No personas with complete data were selected for table generation.")
    write_tabular(output_path, headers=headers, rows=rows)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--self-output",
        type=Path,
        default=SELF_TABLE_PATH,
        help=f"Path for the no-persona table (default: {SELF_TABLE_PATH})",
    )
    parser.add_argument(
        "--persona-output",
        type=Path,
        default=PERSONA_TABLE_PATH,
        help=f"Path for the persona table (default: {PERSONA_TABLE_PATH})",
    )
    parser.add_argument(
        "--persona-ids",
        type=int,
        nargs="+",
        default=DEFAULT_PERSONA_IDS,
        help="Persona IDs to include in the persona table (default: %(default)s)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    generate_self_table(args.self_output)
    generate_persona_table(
        args.persona_output,
        persona_ids=args.persona_ids,
    )


if __name__ == "__main__":
    main()
